### ISSUE TITLE
Fix 'as' positioning issue in ForwarderLevel-Bandwidth_Throttling_Occurring

### ISSUE THREAD

**Issue by swiip81** [gjanders/SplunkAdmins#1]
Hello,

Thank you for this work
 
Please find under an easy thing to fix in default/savedsearches.conf

 search = `comment("This alert detects universal forwarders that have hit the maxKbps setting in the limits.conf and might need to be investigated")` \
 index=_internal "has reached maxKBps. As a result, data forwarding may be throttled" sourcetype=splunkd (`splunkadmins_splunkd_source`) OR (`splunkadmins_splunkuf_source`) \
-| stats count(_raw) by host as countPerHost \
+| stats count(_raw) as countPerHost by host \
 | where countPerHost > 1
 disabled = 1

Regards

**Comment by gjanders** [comment]
Thankyou for finding this, I have now corrected this in github and uploaded a new version to SplunkBase, due to certification it may take 8 days before the update appears there but it is now available on github.

The new search is now:
```
 `comment("This alert detects universal or heavy forwarders that have hit the maxKbps setting in the limits.conf and might need to be investigated")` 
index=_internal "has reached maxKBps. As a result, data forwarding may be throttled" sourcetype=splunkd (`splunkadmins_splunkd_source`) OR (`splunkadmins_splunkuf_source`) 
| bin _time span=1h
| stats count(_raw) as countPerHost by host, _time
| where countPerHost > 1
```

**Comment by gjanders** [comment]
If you just wanted to double check the above I'll close the issue, the reason to use the time-based is so that you see if it's just a temporary issue at a peak time or if it's a longer issue...

**Comment by swiip81** [comment]
Seems good yes. Thank you. Can close it.

But is there any advantage to use 'count(_raw)' instead of just 'count'  , result should be always the same here I guess, but looking for a field may cost a bit more no ?

**Comment by gjanders** [comment]
I wouldn't expect it to, but that is just an old habit that I should remove, I'll update it now and close off this case.
