### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Xyz00777** [gjanders/SplunkAdmins#16]
Hi,
first, AWESOME plugin! looking forward to see more: :)
Your Application dont have app requirements but for some searches it have dependencies like the Splunk Machine Learning Toolkit. can you please add the dependencies for fully funktonality to the description? these would be awesome, possibly also with an description what searches need what additional App.
These would be Awesome!

Greetings

**Comment by gjanders** [comment]
Was this related to the one dashboard I recently added that uses the scatterchart? Or something else?

Thanks

**Comment by gjanders** [comment]
Release 3.0.1 has a mention of this in the README.md now, thanks
