### ISSUE TITLE
Scheduled Searches that cannot run needs optimization

### ISSUE THREAD

**Issue by AHCL1** [gjanders/SplunkAdmins#18]
The search doesn't reveal any hosts, which would be very useful to differentiate between which host is affected. Please remediate it so that it will show the host if you so choose.

**Comment by gjanders** [comment]
I think that should be easy to do. I should have time Monday to update this.

Thanks

**Comment by gjanders** [comment]
Apologies I forgot about this issue but have updated the testing branch now and will try to get that released today

**Comment by gjanders** [comment]
Released version 3.0.8
