### ISSUE TITLE
indexer_cluster_name macro not found

### ISSUE THREAD

**Issue by barrettnet** [gjanders/SplunkAdmins#19]
There are 14 references to a macro called indexer_cluster_name in default/savedsearches.conf   Some of these supply a single argument while others supply none.   default/macros.conf defines [index_cluster_name(1)] which means that those that do not provide an argument are silently failing within an error in index=_internal about the indexer_cluster_name macro not being found.

`index=_internal sourcetype=splunkd TERM(SearchParser) component=SearchParser TERM(ERROR) log_level=ERROR event_message="The search specifies a macro * that cannot be found.*"`

I believe that the fix is to also define a variant of the indexer_cluster_name macro which does not accept any arguments:

```
[indexer_cluster_name]
definition = "default"
iseval = 0
```

**Comment by gjanders** [comment]
Thankyou for finding that, I've put some updates into the testing branch and will try to get that released today

**Comment by gjanders** [comment]
Released version 3.0.8
