### ISSUE TITLE
SavedSearch Detect MongoDB errors

### ISSUE THREAD

**Issue by agiallombardo** [gjanders/SplunkAdmins#2]
Hello,

I highly recommend adding " W " to the savedsearch. Certificates expiring, for example, will show up in W not E OR F.

index=_internal `searchheadhosts` `splunkadmins_mongo_source` (" E " OR " F " OR " **W** ") `splunkadmins_mongodb_errors`\

**Comment by gjanders** [comment]
I only just released a version so will re-release with this need feedback!

**Comment by gjanders** [comment]
Done! New master branch and SplunkBase release have this update

**Comment by gjanders** [comment]
While I have added this, I suspect the warnings may become too noisy depending on the environment. I will wait and see if I receive further feedback.

There is a macro called `splunkadmins_mongodb_errors` which could be used for further filtering if required...
