### ISSUE TITLE
Line 1199 within default/savedsearches.conf is missing a trailing backslash

### ISSUE THREAD

**Issue by barrettnet** [gjanders/SplunkAdmins#20]
Line 1199 within default/savedsearches.conf, which resides within the [SearchHeadLevel - Scheduled Searches That Cannot Run] stanza, is missing a trailing "\\" (backslash).

**Comment by gjanders** [comment]
Thankyou for finding this, I've fixed it in the test branch

**Comment by gjanders** [comment]
Released in 3.0.9
