### ISSUE TITLE
Missing backslashes in default/savedsearches.conf - lines 7804 and 7808

### ISSUE THREAD

**Issue by barrettnet** [gjanders/SplunkAdmins#21]
I'm sorry to say it but lines 7804 and 7808 within 3.0.9's default/savedsearches.conf are both missing backslashes for multiline content.

**Comment by gjanders** [comment]
Thanks, I should have been more careful in copying & pasting / testing :(

**Comment by gjanders** [comment]
Fixed in testing, will run a quick check to see if I missed anything else and will release soon

**Comment by gjanders** [comment]
btool check passes, ksconf check didn't catch this one

**Comment by barrettnet** [comment]
Yeah, 'btool check' is how I've been picking them up.

**Comment by gjanders** [comment]
Released 3.0.10
