### ISSUE TITLE
Error in 'SearchParser'

### ISSUE THREAD

**Issue by SANSd20** [gjanders/SplunkAdmins#22]
When running "MonitoringConsole - Crash logs have appeared on the filesystem", I get the error "Error in 'SearchParser': The search specifies a macro 'indexer_cluster' that cannot be found. Reasons include: the macro name is misspelled, you do not have "read" permission for the macro, or the macro has not been shared with this application. Click Settings, Advanced search, Search Macros to view macro information."

I do not see the macro 'indexer_cluster', the closest I see is 'indexer_cluster_name' or 'indexer_cluster_name(1)'.

**Comment by gjanders** [comment]
Thanks for finding this, that bug was in 1 searches. I have 1  more bug to get fixed so I'll release a new version today with the fixes

**Comment by gjanders** [comment]
Released version 3.0.11, thanks for reporting this one!
