### ISSUE TITLE
Error occured when  ClusterMasterLevel - excess buckets is not executed on the cluster master

### ISSUE THREAD

**Issue by Mojito2110** [gjanders/SplunkAdmins#23]
Error : 
 SearchMessages - orig_component="SearchOperator:rest" app="SplunkAdmins" sid="scheduler__nobody__SplunkAdmins__RMD53c71962112e76a41_at_1707494400_71" message_key="RESTPROC:REST_BAD_URI_PATH" message=Failed to fetch REST endpoint uri=https://127.0.0.1:8089/services/cluster/master/indexes?count=0&f=total_excess%2A from server https://127.0.0.1:8089. Check that the URI path provided exists in the REST API.

 because the search   | rest /services/cluster/master/indexes splunk_server=local works only if is executed on the cluster master

Solution : 
  replace splunk_server=local by the macro splunkadmins_clustermaster_host

**Comment by gjanders** [comment]
I had that issue fixed in the testing branch which I had not yet released, I'll release it soon to fix this issue.

Thanks for raising the issue.

**Comment by gjanders** [comment]
Version 3.0.13 should fix this issue
