### ISSUE TITLE
Line 8411 of default/savedsearches.conf in v4.0.1 is missing a line-continuation marker

### ISSUE THREAD

**Issue by barrettnet** [gjanders/SplunkAdmins#25]
Line 8411 of default/savedsearches.conf in v4.0.1 is missing a line-continuation marker ( \\ ) which causes it to be flagged as an issue/error when running a "btool check".

https://github.com/gjanders/SplunkAdmins/blob/db8de8c1abd9fe2ac55b54f6a410cb39b647fcef/default/savedsearches.conf#L8411

**Comment by gjanders** [comment]
Thanks! I thought appinspect might find these small errors...

I've updated the testing branch and will try to get that released today

**Comment by gjanders** [comment]
Released 4.0.2, let me know if you find any more errors!
