### ISSUE TITLE
Alert Scheduled searches not specifying an index macro version triggers on wildcard in index

### ISSUE THREAD

**Issue by cmeerbeek** [gjanders/SplunkAdmins#5]
Hi,
We got this alert for a search using a macro. The search in the macro started like "index=sec_*_wineventlog". For us this is not an alert. What's your view on this?
Thanks for a great app!

**Comment by gjanders** [comment]
Strange, I attempted to replicate this but it appeared to work just fine.

Here is what I have tested:
Created a macro called: testmacro, contents of `index=sec_*_wineventlog sourcetype=x`
Scheduled a report that calls `testmacro` (with the backticks around it)
Now if I remove the very last line from `SearchHeadLevel - Scheduled searches not specifying an index macro version`, I see my test report, but the last line which is:
`| regex qualifiedSearch!=".*index\s*(!?)=\s*([^*]|\*\S+)"`

Appears to work as expected and does not alert me on that particular alert/report. If you remove the last line is the macro getting substituted as expected?
Is there anything else in there that might confuse the regex?
